import Head from "next/head";
import Banner from "../components/Banner";
import SectionTitle from "../components/SectionTitle";
import CategoryCard from "../components/CategoryCard";
import Section from "../components/Section";
export default function Home({ categories }) {
  console.log(categories);
  return (
    <div>
      <Head>
        <title>
          Delivery de Pedidos a domicilio en minutos | Rappi Argentina
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white">
        <Banner />
        <Section
          backgroundColor={"bg-slate-50"}
          border={"border-b border-slate-250"}
          container={false}
        >
          <div className="pl-10">
            <SectionTitle className="mb-8" text={"Categorías"} />
            <div className="flex space-x-3 overflow-scroll scrollbar-hide">
              {categories.map((category) => (
                <CategoryCard name={category.name} img={category.img} />
              ))}
            </div>
          </div>
        </Section>
        <Section backgroundColor={"bg-white"} container={false}>
          <div className="pl-10">
            <SectionTitle className="mb-8" text={"Categorías"} />
            <div className="flex space-x-3 overflow-scroll scrollbar-hide">
              {categories.map((category) => (
                <CategoryCard name={category.name} img={category.img} />
              ))}
            </div>
          </div>
        </Section>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const categories = await fetch(
    "http://www.assets.corraditobias.com.ar/categories.json"
  )
    .then((res) => res.json())
    .catch((e) => console.log("Categories api error: ", e));

  return {
    props: {
      categories,
    },
  };
}
