import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Delivery de Pedidos a domicilio en minutos | Rappi Argentina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white">
        <section className='search-banner bg-rappi-orange text-white text-4xl text-center h-64 flex items-center justify-center'>
          <h1 className="font-thin">Si tienes <strong className="font-black">Rappi,</strong> tienes Todo.</h1>
        </section>
      </main>
    </div>
  )
}
